# Generated by Django 5.1.2 on 2024-10-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
